name: CI Windows

on: workflow_call

permissions: 
  contents: read

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RELWITHDEBINFO

jobs:
  CI:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: x64
            runner: windows-latest
            msvc_arch: amd64
            vcpkg_triplet: x64-windows
            prebuild_archive: x64-windows
            enable_avif: 1
            enable_heif: 1
            enable_jxl: 1
            enable_ultrahdr: 1
          - arch: x86
            runner: windows-latest
            msvc_arch: amd64_x86
            vcpkg_triplet: x86-windows
            prebuild_archive: x86-windows
            enable_avif: 0
            enable_heif: 0
            enable_jxl: 0
            enable_ultrahdr: 1
          - arch: arm64
            runner: windows-11-arm
            msvc_arch: arm64
            vcpkg_triplet: arm64-windows
            prebuild_archive: amd64_arm64-windows
            enable_avif: 1
            enable_heif: 1
            enable_jxl: 1
            enable_ultrahdr: 1
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.msvc_arch }}

      - name: Install Dependencies
        run: |
          curl -o deps.7z https://raw.githubusercontent.com/libgd/libgd-windows-vcpkg-prebuild/main/${{matrix.prebuild_archive}}.7z
          7z.exe x deps.7z -o${{github.workspace}}\vcpkgusr

      - name: Configure CMake
        run: >
          cmake -G "Ninja"
          -DENABLE_PNG=1 -DENABLE_FREETYPE=1 -DENABLE_JPEG=1
          -DENABLE_GD_FORMATS=1 -DENABLE_TIFF=1
          -DENABLE_HEIF=${{matrix.enable_heif}}
          -DENABLE_AVIF=${{matrix.enable_avif}}
          -DENABLE_JXL=${{matrix.enable_jxl}}
          -DENABLE_PNG=1
          -DENABLE_ULTRAHDR=${{matrix.enable_ultrahdr}}
          -DENABLE_WEBP=1
          -DENABLE_FREETYPE=1
          -DENABLE_ICONV=1
          -DBUILD_TEST=1
          -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          "-DCMAKE_PREFIX_PATH=${{github.workspace}}\vcpkgusr\${{matrix.vcpkg_triplet}}"
          "-DCMAKE_LIBRARY_PATH=${{github.workspace}}\vcpkgusr\${{matrix.vcpkg_triplet}}\lib"
          "-DCMAKE_INCLUDE_PATH=${{github.workspace}}\vcpkgusr\${{matrix.vcpkg_triplet}}\include"

      - name: Build
        run: |
          cd ${{github.workspace}}/build
          cmake --build . --config ${{env.BUILD_TYPE}}

      - name: Tests
        working-directory: ${{github.workspace}}/build
        run: |
          echo ${{runner.temp}}
          echo %TMP%
          echo %TEMP%
          set PATH=${{github.workspace}}\vcpkgusr\${{matrix.vcpkg_triplet}}\bin;%PATH%
          set CTEST_OUTPUT_ON_FAILURE=1
          ctest -C ${{env.BUILD_TYPE}}
