# GitHub actions workflow.
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

name: Codecov

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  codecov:
    runs-on: ubuntu-latest
    env:
      CC: gcc
      CXX: g++
      BUILD_TYPE: Debug
      COVERAGE_FLAGS: --coverage -O0 -g
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: true

    - name: Update apt
      run: sudo apt-get update -qq

    - name: Install dependencies
      run: |
        sudo apt-get install -y \
          cmake \
          g++ \
          gcc \
          libavifile-0.7-dev \
          libde265-dev \
          libfreetype-dev \
          libheif-dev \
          libimagequant-dev \
          libjpeg-turbo8-dev \
          libpng-dev \
          libraqm-dev \
          libtiff5-dev \
          libwebp-dev \
          libx265-dev \
          libxpm-dev

    - name: Configure gd
      run: |
        cmake \
          -DENABLE_CPP=1 \
          -DENABLE_FREETYPE=1 \
          -DENABLE_GD_FORMATS=1 \
          -DENABLE_HEIF=0 \
          -DENABLE_JPEG=1 \
          -DENABLE_PNG=1 \
          -DENABLE_TIFF=1 \
          -DENABLE_WEBP=1 \
          -DBUILD_TEST=1 \
          -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
          -DCMAKE_C_FLAGS="${COVERAGE_FLAGS}" \
          -DCMAKE_CXX_FLAGS="${COVERAGE_FLAGS}" \
          -DCMAKE_EXE_LINKER_FLAGS="--coverage" \
          -DCMAKE_SHARED_LINKER_FLAGS="--coverage" \
          -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${BUILD_TYPE} --parallel 4

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: CTEST_OUTPUT_ON_FAILURE=1 ctest -C ${BUILD_TYPE}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        gcov_executable: gcov
        gcov_include: src
        fail_ci_if_error: true
        verbose: true
